In [133]:
import pandas as pd

In [134]:
df=pd.read_csv("data.csv")

In [135]:
df

,Product ID,Product Title,Merchant ID,Cluster ID,Cluster Label,Category ID,Category Label
0,1,apple iphone 8 plus 64gb silver,1,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
1,2,apple iphone 8 plus 64 gb spacegrau,2,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
2,3,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...,3,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
3,4,apple iphone 8 plus 64gb space grey,4,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
4,5,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,5,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones
...,...,...,...,...,...,...,...
35306,47350,smeg fab28 60cm retro style right hand hinge f...,59,47517,Smeg FAB28 Cream,2623,Fridges
35307,47351,smeg fab28 60cm retro style left hand hinge fr...,59,47518,Smeg FAB28 Red,2623,Fridges
35308,47352,smeg fab28 60cm retro style left hand hinge fr...,59,47519,Smeg FAB28 Pink,2623,Fridges
35309,47355,candy 60cm built under larder fridge cru160nek,125,47524,Candy CRU16.0,2623,Fridges
35310,47358,neff k4316x7gb built under larder fridge,179,47525,Neff K4316,2623,Fridges

In [136]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import nltk

In [137]:
stemmer=PorterStemmer()
lemmatizer=WordNetLemmatizer()

In [138]:
def tokenize_sentences(text):
    return nltk.sent_tokenize(text)

def stem_text(text):
    tokens=nltk.word_tokenize(text)
    return " ".join(stemmer.stem(token) for token in tokens)

def lemmatize_text(text):
    tokens=nltk.word_tokenize(text)
    return " ".join(lemmatizer.lemmatize(token) for token in tokens)

In [139]:
df['Sentences']=df[' Cluster Label'].apply(tokenize_sentences)
df['Sentences_product']=df['Product Title'].apply(tokenize_sentences)
df['Stemmed']=df[' Cluster Label'].apply(stem_text)
df['Stemmed_product']=df['Product Title'].apply(stem_text)

In [140]:
df['lemmatized']=df[' Cluster Label'].apply(lemmatize_text)
df['lemmatized_product']=df['Product Title'].apply(lemmatize_text)

In [141]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [142]:
df

,Product ID,Product Title,Merchant ID,Cluster ID,Cluster Label,Category ID,Category Label,Sentences,Sentences_product,Stemmed,Stemmed_product,lemmatized,lemmatized_product
0,1,apple iphone 8 plus 64gb silver,1,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones,[Apple iPhone 8 Plus 64GB],[apple iphone 8 plus 64gb silver],appl iphon 8 plu 64gb,appl iphon 8 plu 64gb silver,Apple iPhone 8 Plus 64GB,apple iphone 8 plus 64gb silver
1,2,apple iphone 8 plus 64 gb spacegrau,2,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones,[Apple iPhone 8 Plus 64GB],[apple iphone 8 plus 64 gb spacegrau],appl iphon 8 plu 64gb,appl iphon 8 plu 64 gb spacegrau,Apple iPhone 8 Plus 64GB,apple iphone 8 plus 64 gb spacegrau
2,3,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...,3,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones,[Apple iPhone 8 Plus 64GB],[apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp si...,appl iphon 8 plu 64gb,appl mq8n2b/a iphon 8 plu 64gb 5.5 12mp sim fr...,Apple iPhone 8 Plus 64GB,apple mq8n2b/a iphone 8 plus 64gb 5.5 12mp sim...
3,4,apple iphone 8 plus 64gb space grey,4,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones,[Apple iPhone 8 Plus 64GB],[apple iphone 8 plus 64gb space grey],appl iphon 8 plu 64gb,appl iphon 8 plu 64gb space grey,Apple iPhone 8 Plus 64GB,apple iphone 8 plus 64gb space grey
4,5,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...,5,1,Apple iPhone 8 Plus 64GB,2612,Mobile Phones,[Apple iPhone 8 Plus 64GB],[apple iphone 8 plus gold 5.5 64gb 4g unlocked...,appl iphon 8 plu 64gb,appl iphon 8 plu gold 5.5 64gb 4g unlock sim free,Apple iPhone 8 Plus 64GB,apple iphone 8 plus gold 5.5 64gb 4g unlocked ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35306,47350,smeg fab28 60cm retro style right hand hinge f...,59,47517,Smeg FAB28 Cream,2623,Fridges,[Smeg FAB28 Cream],[smeg fab28 60cm retro style right hand hinge ...,smeg fab28 cream,smeg fab28 60cm retro style right hand hing fr...,Smeg FAB28 Cream,smeg fab28 60cm retro style right hand hinge f...
35307,47351,smeg fab28 60cm retro style left hand hinge fr...,59,47518,Smeg FAB28 Red,2623,Fridges,[Smeg FAB28 Red],[smeg fab28 60cm retro style left hand hinge f...,smeg fab28 red,smeg fab28 60cm retro style left hand hing fri...,Smeg FAB28 Red,smeg fab28 60cm retro style left hand hinge fr...
35308,47352,smeg fab28 60cm retro style left hand hinge fr...,59,47519,Smeg FAB28 Pink,2623,Fridges,[Smeg FAB28 Pink],[smeg fab28 60cm retro style left hand hinge f...,smeg fab28 pink,smeg fab28 60cm retro style left hand hing fri...,Smeg FAB28 Pink,smeg fab28 60cm retro style left hand hinge fr...
35309,47355,candy 60cm built under larder fridge cru160nek,125,47524,Candy CRU16.0,2623,Fridges,[Candy CRU16.0],[candy 60cm built under larder fridge cru160nek],candi cru16.0,candi 60cm built under larder fridg cru160nek,Candy CRU16.0,candy 60cm built under larder fridge cru160nek
35310,47358,neff k4316x7gb built under larder fridge,179,47525,Neff K4316,2623,Fridges,[Neff K4316],[neff k4316x7gb built under larder fridge],neff k4316,neff k4316x7gb built under larder fridg,Neff K4316,neff k4316x7gb built under larder fridge

In [143]:
from sklearn.feature_extraction.text import CountVectorizer

In [144]:
cv=CountVectorizer(ngram_range=(3,3),binary=True)

In [ ]:
y=cv.fit_transform(df['Product Title'],)

In [146]:
y

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 220087 stored elements and shape (35311, 92938)>

In [149]:
y

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 220087 stored elements and shape (35311, 92938)>